### ISSUE TITLE
error main not found

### ISSUE THREAD

**Issue by hasanAjsf** [davidB/hello_rs_overdesign#1]
Either I did not understand how to use it, or it is not matching my needs, for simple `println!()` statement I got below error

![image](https://user-images.githubusercontent.com/46838626/64428995-b4123800-d0bd-11e9-9b89-68d115af7449.png)

**Comment by davidB** [comment]
I never saw this error before (TBH I didn't test this config on windows).
Did you save before run ?

The tempCodeRunnerFile.rs doesn't seem to contain `main`(or the content of your file)

**Comment by hasanAjsf** [comment]
> Did you save before run ?

Yes, actually I opened a saved file and just run this without any changes.

**Comment by davidB** [comment]
It's because you select a line (the vscode plugin "code runner" create a rust file with only your selection see [code runner 's features](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner)).

![Imgur](https://i.imgur.com/c08IliZ.png)

![Imgur](https://i.imgur.com/IisFth0.png)

**Comment by hasanAjsf** [comment]
Thanks a lot.
